export const CABIN_CLASSES ={
    BUSINESS_CLASS:'BUSINESS_CLASS',
    ECONOMY_CLASS:'ECONOMY_CLASS',
}
export const SERVICE_TYPES ={
    CHOOSE_MEAL:'CHOOSE_MEAL',
    DELETE_MEAL:'DELETE_MEAL',
    CHOOSE_SEAT:'CHOOSE_SEAT',
    DELETE_SEAT:'DELETE_SEAT',
}
export const AIRLINE_TYPES ={
    TURKISH:'TURKISH',
    UZ_AIRWAYS:'UZ_AIRWAYS',
    CHARTER_FLIGHTS:'CHARTER_FLIGHTS',
    AZERBAIJAN_AIRLINES :'AZERBAIJAN_AIRLINES ',
}
export const PAYMENT_METHODS ={
    CLICK:'CLICK',
    PAYME:'PAYME',
    APELSIN:'APELSIN',
    OSON :'OSON ',
    MASTERCARD :'MASTERCARD ',
    VISA :'VISA ',
    PAYNET :'PAYNET ',
    STRIPE :'STRIPE ',
    YANDEX_MONEY  :'YANDEX_MONEY  ',
}